CRMversion1/CRMversion1/urls.py
from django.conf.urls import url
from django.contrib import admin
from crm_app_01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 首页
    url(r'^index/', views.index, name='index'),
    # 注册
    url(r'^register/', views.register, name='register'),
    # 登录
    url(r'^login/', views.login, name='login'),
    # 验证码
    url(r'^get_valid_img/', views.get_valid_img, name='get_valid_img'),
    # 注销
    url(r'^logout/', views.logout, name='logout'),
    # url(r'^shopping/', views.shopping, name='shopping'),
    # 展示所有客户信息
    url(r'^customers/list/', views.Customers.as_view(), name='customers'),

    # 分页
    url(r'^test/', views.test, name='test'),

    # 添加
    url(r'^add/', views.AddCustomer.as_view(), name='addcustomer'),
    # 编辑
    url(r'^editcustomer/(\d+)/', views.EditCustomer.as_view(), name='editcustomer'),
    # 删除
    url(r'^deletecustomer/(\d+)/', views.DeleteCustomer.as_view(), name='deletecustomer'),
    # 搜索
    # url(r'^customers/list/?condition', views.Search.as_view(), name='search'),

]

CRMversion1/crm_app_01/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django import forms
#安装:pip install django-multiselectfield,针对choices多选用的

from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)

class UserInfo(AbstractUser):
    #销售,班主任,讲师,三哥
    telephone = models.CharField(max_length=32,null=True)


class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)

    phone = models.CharField('手机号', blank=True, null=True,max_length=32)
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)  #self指的就是自己这个表，和下面写法是一样的效果


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices,null=True,blank=True) #多选，并且存成一个列表的格式
    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True)

    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True)


    #一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",null=True,blank=True )


    def __str__(self):
        return self.name+":"+self.qq  #主要__str__最好是个字符串昂，不然你会遇到很多的坑，还有我们返回的这两个字段填写数据的时候必须写上数据，必然相加会报错，null类型和str类型不能相加等错误信息。


    def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用

        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        # return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂
        return ",".join(l) #纯文本，不用mark_safe也可以昂


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name




class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True) #不一定什么时候结业，哈哈，所以可为空

    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师") #对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)

CRMversion1/templates/add.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="{% url 'addcustomer' %}" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>


                    {% endfor %}

                <button class="btn btn-primary pull-right">提交</button>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

CRMversion1/templates/customers.html
{% extends 'base.html' %}

{% block content %}

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">客户信息展示</h3>


                    </div>
                    <form method="get">
                        {#                        <input type="text" name="kw">#}


                            <select name="condition" id="" >
                                <option value="name">姓名</option>
                                <option value="qq">QQ</option>
                            </select>

                                <input type="text"  name="kw">

                            <a href="{% url 'addcustomer' %}" class="btn btn-success pull-right">添加信息</a>
                            <button class="btn btn-primary">搜索</button>




                    </form>

                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>qq</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>客户来源</th>
                                <th>转介绍自学员</th>
                                <th>咨询课程</th>
                                {#                                <th>选择客户此时的状态</th>#}
                                {#                                <th>销售</th>#}
                                {#                                <th>已报班级</th>#}
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for customer in all_customers %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ customer.qq }}</td>
                                    <td>{{ customer.name }}</td>
                                    <td>{{ customer.get_sex_display }}</td>
                                    <td>{{ customer.get_source_display }}</td>
                                    <td>{{ customer.introduce_from.name }}</td>
                                    <td>{{ customer.course }}</td>
                                    {#                                        <td>{{ customer.get_status_display }}</td>#}
                                    {#                                        <td>{{ customer.consultant.username }}</td>#}
                                    {#                                        <td>{{ customer.get_classlist }}</td>#}

                                    <td>
                                        <a href="{% url 'editcustomer' customer.pk %}"
                                           class="btn btn-warning btn-xs">编辑</a>
                                        <a href="{% url 'deletecustomer' customer.pk %}" class="btn btn-danger btn-xs">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

    {{ ret_html|safe }}

{% endblock %}

CRMversion1/templates/del.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

    </style>
</head>
<body>


<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script>

</script>
</body>
</html>

CRMversion1/templates/edit.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>


                    {% endfor %}

                <button class="btn btn-primary pull-right">提交</button>

                </form>
            </div>
        </div>

    </div>


{% endblock %}

CRMversion1/templates/index.html
{% extends 'base.html' %}

CRMversion1/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<h1>NBCRM登录页面</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" name="username" id="username">
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" name="password" id="password">
                </div>
                <div class="row">
                    <div class="col-md-6 col-xs-6">
                        <div class="form-group">
                            <label for="valid_code">验证码</label>
                            <input type="text" class="form-control" name="valid_code" id="valid_code">
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-6">
                        <img id="valid_code_img" src="{% url 'get_valid_img' %}" alt="" style="margin-top: 24px;">
                    </div>
                </div>
                <span id="error" class="text-danger"></span>
                <input id="login" type="button" value="登录" class="btn btn-primary pull-right">

            </form>

        </div>
    </div>
</div>


<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script>

    $('#login').on('click',function () {
        var username = $('[name=username]').val();
        var password = $('[name=password]').val();
        var valid_code = $('[name=valid_code]').val();
        var csrf_token = $('[name=csrfmiddlewaretoken]').val();

        $.ajax({
            url:{% url "login" %},
            type:'post',
            data:{
              username:username,
              password:password,
              valid_code:valid_code,
              csrfmiddlewaretoken:csrf_token,
            },
            success:function (res) {
                //{'code':1000,'msg':'xxx'}
                if (res.code === 1000){
                    {#location.href = {% url 'index' %};#}
                    var href = location.search.slice(6);
                    if (href){
                        location.href = href;
                    }else {
                        location.href = {% url 'index' %};
                    }

                }
                else {
                    $('#error').text(res.msg);
                }


            }

        })


    });

    //点击图片刷新验证码
    $('#valid_code_img').click(function () {
        $(this)[0].src += '?';
    })

</script>
</body>
</html>

CRMversion1/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<h1>这是注册页面</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="{% url 'register' %}" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="text-danger">{{ field.errors.0 }}</span>
                    </div>

                {% endfor %}

                <input type="submit" class="btn btn-success pull-right" value="注册">

            </form>

        </div>
    </div>

</div>


<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script>


</script>
</body>
</html>

CRMversion1/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<h1>这是test</h1>
<form action="" method="get">
    <select name="condition" id="">
        <option value="name">姓名</option>
        <option value="qq">QQ</option>
    </select>
    <input type="text" name="kw"> <button>搜索</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>QQ</th>
            <th>名称</th>
        </tr>
    </thead>
    <tbody>
        {% for data in all_data %}
            <tr>
                <td>{{ data.qq }}</td>
                <td>{{ data.name }}</td>
            </tr>
        {% endfor %}

    </tbody>
</table>

{{ ret_html|safe }}




<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script>


</script>
</body>
</html>

CRMversion1/templates/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

    </style>
</head>
<body>
<h1>这是test页面</h1>
<table class="table">
    <thead>
    <tr>
        <th>名称</th>
    </tr>
    </thead>
    <tbody>
      {% for data in all_data %}
    <tr>
        <td>{{ data.name }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{{ ret_html|safe }}
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script>

</script>
</body>
</html>